# application configuration
# server:
#   port: 8081

### keycloak configuration
keycloak:
  realm: cvmanager
  resource: cvmanager-gui # client id
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8084}
keycloak_username: ${KEYCLOAK_ADMIN:admin}
keycloak_password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
spring.security.oauth2.resourceserver.jwt:
  issuer-uri: ${AUTH_SERVER_URL:http://localhost:8084}/realms/cvmanager
  jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:8084}/realms/cvmanager/protocol/openid-connect/certs

spring.kafka.bootstrap-servers: ${KAFKA_BROKER_IP:localhost}:${KAFKA_BROKER_PORT:9092}
logging.level.org.apache.kafka: INFO
logging.level: INFO

schema.bsm: classpath:schemas/bsm.schema.json
schema.map: classpath:schemas/map.schema.json
schema.spat: classpath:schemas/spat.schema.json

kafka.topics:
  autoCreateTopics: false
  numPartitions: 1
  numReplicas: 1
  createTopics:
    - name: topic.ProcessedSpat
      cleanupPolicy: delete
      retentionMs: 300000
    - name: topic.ProcessedMap
      cleanupPolicy: delete
      retentionMs: 300000
