include:
  - ./jpo-utils/docker-compose-kafka.yml
  - ./jpo-utils/docker-compose-mongo.yml

services:
  intersection_api:
    profiles:
      - intersection
      - intersection_api
    image: intersection-api:latest
    build:
      context: ./services
      dockerfile: Dockerfile.intersection-api
      args:
        MAVEN_GITHUB_TOKEN: ${MAVEN_GITHUB_TOKEN:?error}
        MAVEN_GITHUB_ORG: ${MAVEN_GITHUB_ORG:-usdot-jpo-ode}
    ports:
      - '8089:8089'
    restart: always
    environment:
      AUTH_SERVER_URL: ${KEYCLOAK_ENDPOINT:-http://${DOCKER_HOST_IP:?error}:8084}
      DB_HOST_IP: ${DB_HOST_IP:-mongo}
      DB_HOST_PORT: ${DB_HOST_PORT:-27017}
      SPRING_KAFKA_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      CM_SERVER_URL: ${CM_SERVER_URL:-http://conflictmonitor:8082}
      load: 'false'
      KAFKA_TYPE: 'ON-PREM'
      ACM_CONFIG_FILE: adm.properties
      ACM_LOG_TO_CONSOLE: true
      ACM_LOG_TO_FILE: false
      ACM_LOG_LEVEL: DEBUG
      MONGO_READ_WRITE_USER: ${MONGO_READ_WRITE_USER:-ode}
      MONGO_READ_WRITE_PASS: ${MONGO_READ_WRITE_PASS:-replace_me}
      CM_MAXIMUM_RESPONSE_SIZE: ${CM_MAXIMUM_RESPONSE_SIZE:-10000}
      SPRING_DATA_MONGODB_DATABASE: ${CM_DATABASE_NAME:-CV}

      KEYCLOAK_CLIENT_API_ID: ${KEYCLOAK_API_CLIENT_ID:-cvmanager-api}
      KEYCLOAK_CLIENT_API_SECRET: ${KEYCLOAK_API_CLIENT_SECRET_KEY:-keycloak-secret-key}

      KAFKA_BROKER_IP: ${KAFKA_BROKER_IP:-kafka}
      KAFKA_BROKER_PORT: ${KAFKA_BROKER_PORT:-5432}

      PG_DB_USER: ${PG_DB_USER:-postgres}
      PG_DB_PASS: ${PG_DB_PASS:-postgres}
      POSTGRES_SERVER_URL: jdbc:postgresql://${PG_DB_HOST:-cvmanager_postgres:5432}

      INTERSECTION_API_ENABLE_API: ${INTERSECTION_API_ENABLE_API:-True}
      INTERSECTION_API_ENABLE_EMAILER: ${INTERSECTION_API_ENABLE_EMAILER:-true}
      INTERSECTION_API_ENABLE_REPORTS: ${INTERSECTION_API_ENABLE_REPORTS:-false}
      INTERSECTION_API_ENABLE_HAAS: ${INTERSECTION_API_ENABLE_HAAS:-false}
      INTERSECTION_API_ENABLE_ASN1_DECODER: ${INTERSECTION_API_ENABLE_ASN1_DECODER:-true}

      FIRMWARE_MANAGER_ENDPOINT: ${FIRMWARE_MANAGER_ENDPOINT:-http://firmware_manager_upgrade_scheduler:8080}

      BASE_ROUTE_PREFIX: ${INTERSECTION_API_ROUTE_PREFIX:-/}

      INTERSECTION_EMAIL_BROKER: ${INTERSECTION_EMAIL_BROKER:-SMTP}
      INTERSECTION_SENDER_EMAIL: ${INTERSECTION_SENDER_EMAIL:-donotreply@cvmanager.com}
      UNSUBSCRIBE_SECRET_KEY: ${UNSUBSCRIBE_SECRET_KEY:-b5f9070ca58d4576ea6a2d8d4c1b97caf8abc2554198f8f9acf86d0d31a52a52}
      CV_MANAGER_FRONT_END_URI: ${CV_MANAGER_FRONT_END_URI:-http://localhost:${WEBAPP_PORT:-3000}}
      INTERSECTION_SMTP_SERVER_HOST: ${INTERSECTION_SMTP_SERVER_HOST:-smtp4dev}
      INTERSECTION_SMTP_SERVER_PORT: ${INTERSECTION_SMTP_SERVER_PORT:-25}
      INTERSECTION_SMTP_USERNAME: ${INTERSECTION_SMTP_USERNAME:-admin}
      INTERSECTION_SMTP_PASSWORD: ${INTERSECTION_SMTP_PASSWORD:-password}
      INTERSECTION_SMTP_AUTH: ${INTERSECTION_SMTP_AUTH_ENABLED:-true}
      INTERSECTION_SMTP_STARTTLS: ${INTERSECTION_SMTP_STARTTLS_ENABLED:-false}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      POSTMARK_API_KEY: ${POSTMARK_API_KEY}
      EMAIL_RATE_LIMIT_PER_USER: ${EMAIL_RATE_LIMIT_PER_USER:-12}
      EMAIL_RATE_LIMIT_PER_INSTANCE: ${EMAIL_RATE_LIMIT_PER_INSTANCE:-120}
    entrypoint:
      - sh
      - -c
      - |
        java -Djava.rmi.server.hostname=$DOCKER_HOST_IP -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dlogback.configurationFile=/home/logback.xml -jar /home/intersection-api.jar
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    depends_on:
      cvmanager_keycloak:
        condition: service_healthy
        required: false
      mongo:
        condition: service_healthy
        required: false
      kafka-setup:
        condition: service_started
        required: false
  smtp4dev:
    profiles:
      - smtp4dev
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80' # Web UI
      - '25:25' # SMTP
    environment:
      # Enable SMTP authentication
      - ServerOptions__AuthenticationRequired=true
      # Set username and password for SMTP auth
      - ServerOptions__Users__0__Username=${SMTP4DEV_USERNAME:-admin}
      - ServerOptions__Users__0__Password=${SMTP4DEV_PASSWORD:-password}
