from common.util import get_env_var

UPGRADE_RUNNER_ENDPOINT=get_env_var("UPGRADE_RUNNER_ENDPOINT", "UNDEFINED")
ACTIVE_UPGRADE_LIMIT=int(get_env_var("ACTIVE_UPGRADE_LIMIT", "20"))
FW_UPGRADE_MAX_RETRY_LIMIT=int(get_env_var("FW_UPGRADE_MAX_RETRY_LIMIT", "3"))