# Confluent properties
spring:
  config:
    activate:
      on-profile: 'confluent'
  kafka:
    properties:
      ssl.endpoint.identification.algorithm: https
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${CONFLUENT_KEY:user}" password="${CONFLUENT_SECRET:pass}";
