import { ReportMetadata } from '../../../../apis/intersections/reports-api'

export const sampleReports: ReportMetadata[] = [
  {
    reportName: 'Intersection_1234_Weekly_Assessment',
    intersectionID: 1234,
    roadRegulatorID: 'RR-789',
    reportGeneratedAt: new Date('2025-03-15T14:30:00Z'),
    reportStartTime: new Date('2025-03-08T12:00:00Z'),
    reportStopTime: new Date('2025-03-15T12:00:00Z'),
    reportContents: ['Lane Direction of Travel', 'Signal State Events', 'Connection of Travel'],
    laneDirectionOfTravelEventCounts: [
      { id: '1', count: 347 },
      { id: '2', count: 289 },
      { id: '3', count: 412 },
    ],
    laneDirectionOfTravelMedianDistanceDistribution: [
      { id: '0-0.5', count: 145 },
      { id: '0.5-1.0', count: 237 },
      { id: '1.0-1.5', count: 402 },
      { id: '1.5+', count: 264 },
    ],
    laneDirectionOfTravelMedianHeadingDistribution: [
      { id: '0-2', count: 324 },
      { id: '2-5', count: 485 },
      { id: '5-10', count: 198 },
      { id: '10+', count: 41 },
    ],
    laneDirectionOfTravelReportData: [
      { timestamp: 1743434775000, laneID: 1, segmentID: 1, headingDelta: 2.3, medianCenterlineDistance: 0.78 },
      { timestamp: 1743434785000, laneID: 2, segmentID: 2, headingDelta: 1.1, medianCenterlineDistance: 0.45 },
      { timestamp: 1743434795000, laneID: 3, segmentID: 1, headingDelta: 3.6, medianCenterlineDistance: 1.23 },
      { timestamp: 1743434805000, laneID: 1, segmentID: 3, headingDelta: 0.9, medianCenterlineDistance: 0.31 },
    ],
    connectionOfTravelEventCounts: [
      { id: 'valid', count: 2358 },
      { id: 'invalid', count: 167 },
    ],
    signalStateConflictEventCount: [{ id: 'total', count: 24 }],
    signalStateEventCounts: [
      { id: 'red', count: 1024 },
      { id: 'yellow', count: 326 },
      { id: 'green', count: 1452 },
    ],
    signalStateStopEventCounts: [
      { id: 'stopped', count: 957 },
      { id: 'no-stop', count: 214 },
    ],
    timeChangeDetailsEventCount: [{ id: 'total', count: 128 }],
    intersectionReferenceAlignmentEventCounts: [
      { id: 'aligned', count: 6793 },
      { id: 'misaligned', count: 82 },
    ],
    mapBroadcastRateEventCount: [{ id: 'total', count: 84 }],
    mapMinimumDataEventCount: [{ id: 'total', count: 37 }],
    spatMinimumDataEventCount: [{ id: 'total', count: 52 }],
    spatBroadcastRateEventCount: [{ id: 'total', count: 78 }],
    latestMapMinimumDataEventMissingElements: ['laneWidth', 'speedLimit'],
    latestSpatMinimumDataEventMissingElements: ['signalPhaseTime'],
    validConnectionOfTravelData: [
      { connectionID: 1, ingressLaneID: 101, egressLaneID: 201, eventCount: 845 },
      { connectionID: 2, ingressLaneID: 102, egressLaneID: 202, eventCount: 762 },
      { connectionID: 3, ingressLaneID: 103, egressLaneID: 203, eventCount: 751 },
    ],
    invalidConnectionOfTravelData: [
      { connectionID: 4, ingressLaneID: 104, egressLaneID: 204, eventCount: 48 },
      { connectionID: 5, ingressLaneID: 105, egressLaneID: 205, eventCount: 62 },
      { connectionID: 6, ingressLaneID: 106, egressLaneID: 206, eventCount: 57 },
    ],
    headingTolerance: 5,
    distanceTolerance: 1.5,
    stopLineStopReportData: [
      {
        signalGroup: 1,
        numberOfEvents: 328,
        timeStoppedOnRed: 3254,
        timeStoppedOnYellow: 142,
        timeStoppedOnGreen: 65,
        timeStoppedOnDark: 12,
      },
      {
        signalGroup: 2,
        numberOfEvents: 297,
        timeStoppedOnRed: 2987,
        timeStoppedOnYellow: 112,
        timeStoppedOnGreen: 43,
        timeStoppedOnDark: 8,
      },
    ],
    stopLinePassageReportData: [
      {
        signalGroup: 1,
        totalEvents: 643,
        redEvents: 24,
        yellowEvents: 87,
        greenEvents: 532,
        darkEvents: 0,
      },
      {
        signalGroup: 2,
        totalEvents: 586,
        redEvents: 18,
        yellowEvents: 63,
        greenEvents: 505,
        darkEvents: 0,
      },
    ],
  },

  {
    reportName: 'Intersection_5678_Daily_Assessment',
    intersectionID: 5678,
    roadRegulatorID: 'RR-456',
    reportGeneratedAt: new Date('2025-04-01T08:15:00Z'),
    reportStartTime: new Date('2025-03-31T00:00:00Z'),
    reportStopTime: new Date('2025-04-01T00:00:00Z'),
    reportContents: ['Lane Direction of Travel', 'MAP Broadcast', 'SPaT Broadcast'],
    laneDirectionOfTravelEventCounts: [
      { id: '1', count: 124 },
      { id: '2', count: 156 },
    ],
    laneDirectionOfTravelMedianDistanceDistribution: [
      { id: '0-0.5', count: 56 },
      { id: '0.5-1.0', count: 89 },
      { id: '1.0-1.5', count: 78 },
      { id: '1.5+', count: 57 },
    ],
    laneDirectionOfTravelMedianHeadingDistribution: [
      { id: '0-2', count: 112 },
      { id: '2-5', count: 87 },
      { id: '5-10', count: 62 },
      { id: '10+', count: 19 },
    ],
    laneDirectionOfTravelReportData: [
      { timestamp: 1743521175000, laneID: 1, segmentID: 1, headingDelta: 1.7, medianCenterlineDistance: 0.67 },
      { timestamp: 1743521185000, laneID: 2, segmentID: 1, headingDelta: 2.2, medianCenterlineDistance: 0.88 },
      { timestamp: 1743521195000, laneID: 1, segmentID: 2, headingDelta: 1.5, medianCenterlineDistance: 0.54 },
    ],
    connectionOfTravelEventCounts: [
      { id: 'valid', count: 468 },
      { id: 'invalid', count: 32 },
    ],
    signalStateConflictEventCount: [{ id: 'total', count: 4 }],
    signalStateEventCounts: [
      { id: 'red', count: 286 },
      { id: 'yellow', count: 68 },
      { id: 'green', count: 325 },
    ],
    signalStateStopEventCounts: [
      { id: 'stopped', count: 243 },
      { id: 'no-stop', count: 43 },
    ],
    timeChangeDetailsEventCount: [{ id: 'total', count: 32 }],
    intersectionReferenceAlignmentEventCounts: [
      { id: 'aligned', count: 1285 },
      { id: 'misaligned', count: 15 },
    ],
    mapBroadcastRateEventCount: [{ id: 'total', count: 18 }],
    mapMinimumDataEventCount: [{ id: 'total', count: 7 }],
    spatMinimumDataEventCount: [{ id: 'total', count: 12 }],
    spatBroadcastRateEventCount: [{ id: 'total', count: 21 }],
    latestMapMinimumDataEventMissingElements: ['laneOffset'],
    latestSpatMinimumDataEventMissingElements: [],
    validConnectionOfTravelData: [
      { connectionID: 1, ingressLaneID: 101, egressLaneID: 201, eventCount: 248 },
      { connectionID: 2, ingressLaneID: 102, egressLaneID: 202, eventCount: 220 },
    ],
    invalidConnectionOfTravelData: [
      { connectionID: 3, ingressLaneID: 103, egressLaneID: 203, eventCount: 16 },
      { connectionID: 4, ingressLaneID: 104, egressLaneID: 204, eventCount: 16 },
    ],
    headingTolerance: 6,
    distanceTolerance: 2.0,
    stopLineStopReportData: [
      {
        signalGroup: 1,
        numberOfEvents: 142,
        timeStoppedOnRed: 1456,
        timeStoppedOnYellow: 45,
        timeStoppedOnGreen: 12,
        timeStoppedOnDark: 0,
      },
      {
        signalGroup: 2,
        numberOfEvents: 101,
        timeStoppedOnRed: 954,
        timeStoppedOnYellow: 37,
        timeStoppedOnGreen: 6,
        timeStoppedOnDark: 0,
      },
    ],
    stopLinePassageReportData: [
      {
        signalGroup: 1,
        totalEvents: 187,
        redEvents: 6,
        yellowEvents: 23,
        greenEvents: 158,
        darkEvents: 0,
      },
      {
        signalGroup: 2,
        totalEvents: 164,
        redEvents: 4,
        yellowEvents: 17,
        greenEvents: 143,
        darkEvents: 0,
      },
    ],
  },

  {
    reportName: 'Intersection_9012_Monthly_Assessment',
    intersectionID: 9012,
    roadRegulatorID: 'RR-123',
    reportGeneratedAt: new Date('2025-03-31T23:45:00Z'),
    reportStartTime: new Date('2025-03-01T12:00:00Z'),
    reportStopTime: new Date('2025-04-01T12:00:00Z'),
    reportContents: ['All Assessment Types'],
    laneDirectionOfTravelEventCounts: [
      { id: '1', count: 3468 },
      { id: '2', count: 2956 },
      { id: '3', count: 3187 },
      { id: '4', count: 2745 },
    ],
    laneDirectionOfTravelMedianDistanceDistribution: [
      { id: '0-0.5', count: 4235 },
      { id: '0.5-1.0', count: 3876 },
      { id: '1.0-1.5', count: 2654 },
      { id: '1.5+', count: 1591 },
    ],
    laneDirectionOfTravelMedianHeadingDistribution: [
      { id: '0-2', count: 5842 },
      { id: '2-5', count: 3789 },
      { id: '5-10', count: 1986 },
      { id: '10+', count: 739 },
    ],
    laneDirectionOfTravelReportData: [
      { timestamp: 1741743375000, laneID: 1, segmentID: 1, headingDelta: 1.2, medianCenterlineDistance: 0.43 },
      { timestamp: 1741743675000, laneID: 2, segmentID: 1, headingDelta: 2.5, medianCenterlineDistance: 0.78 },
      { timestamp: 1741743975000, laneID: 3, segmentID: 2, headingDelta: 1.8, medianCenterlineDistance: 0.65 },
      { timestamp: 1741744275000, laneID: 4, segmentID: 2, headingDelta: 3.2, medianCenterlineDistance: 0.92 },
    ],
    connectionOfTravelEventCounts: [
      { id: 'valid', count: 29456 },
      { id: 'invalid', count: 1842 },
    ],
    signalStateConflictEventCount: [{ id: 'total', count: 183 }],
    signalStateEventCounts: [
      { id: 'red', count: 10256 },
      { id: 'yellow', count: 3248 },
      { id: 'green', count: 17984 },
    ],
    signalStateStopEventCounts: [
      { id: 'stopped', count: 9654 },
      { id: 'no-stop', count: 602 },
    ],
    timeChangeDetailsEventCount: [{ id: 'total', count: 1284 }],
    intersectionReferenceAlignmentEventCounts: [
      { id: 'aligned', count: 64285 },
      { id: 'misaligned', count: 957 },
    ],
    mapBroadcastRateEventCount: [{ id: 'total', count: 324 }],
    mapMinimumDataEventCount: [{ id: 'total', count: 148 }],
    spatMinimumDataEventCount: [{ id: 'total', count: 186 }],
    spatBroadcastRateEventCount: [{ id: 'total', count: 289 }],
    latestMapMinimumDataEventMissingElements: ['speedLimit', 'maneuverAssist', 'laneWidth'],
    latestSpatMinimumDataEventMissingElements: ['signalGroupID', 'signalPhaseTime'],
    validConnectionOfTravelData: [
      { connectionID: 1, ingressLaneID: 101, egressLaneID: 201, eventCount: 7845 },
      { connectionID: 2, ingressLaneID: 102, egressLaneID: 202, eventCount: 7284 },
      { connectionID: 3, ingressLaneID: 103, egressLaneID: 203, eventCount: 7621 },
      { connectionID: 4, ingressLaneID: 104, egressLaneID: 204, eventCount: 6706 },
    ],
    invalidConnectionOfTravelData: [
      { connectionID: 5, ingressLaneID: 105, egressLaneID: 205, eventCount: 546 },
      { connectionID: 6, ingressLaneID: 106, egressLaneID: 206, eventCount: 487 },
      { connectionID: 7, ingressLaneID: 107, egressLaneID: 207, eventCount: 512 },
      { connectionID: 8, ingressLaneID: 108, egressLaneID: 208, eventCount: 297 },
    ],
    headingTolerance: 4,
    distanceTolerance: 1.2,
    stopLineStopReportData: [
      {
        signalGroup: 1,
        numberOfEvents: 2487,
        timeStoppedOnRed: 32456,
        timeStoppedOnYellow: 1248,
        timeStoppedOnGreen: 372,
        timeStoppedOnDark: 65,
      },
      {
        signalGroup: 2,
        numberOfEvents: 2354,
        timeStoppedOnRed: 29785,
        timeStoppedOnYellow: 1087,
        timeStoppedOnGreen: 289,
        timeStoppedOnDark: 42,
      },
      {
        signalGroup: 3,
        numberOfEvents: 2568,
        timeStoppedOnRed: 33256,
        timeStoppedOnYellow: 1386,
        timeStoppedOnGreen: 298,
        timeStoppedOnDark: 58,
      },
      {
        signalGroup: 4,
        numberOfEvents: 2245,
        timeStoppedOnRed: 27856,
        timeStoppedOnYellow: 984,
        timeStoppedOnGreen: 254,
        timeStoppedOnDark: 37,
      },
    ],
    stopLinePassageReportData: [
      {
        signalGroup: 1,
        totalEvents: 6578,
        redEvents: 234,
        yellowEvents: 865,
        greenEvents: 5479,
        darkEvents: 0,
      },
      {
        signalGroup: 2,
        totalEvents: 5946,
        redEvents: 187,
        yellowEvents: 748,
        greenEvents: 5011,
        darkEvents: 0,
      },
      {
        signalGroup: 3,
        totalEvents: 6243,
        redEvents: 214,
        yellowEvents: 812,
        greenEvents: 5217,
        darkEvents: 0,
      },
      {
        signalGroup: 4,
        totalEvents: 5689,
        redEvents: 165,
        yellowEvents: 698,
        greenEvents: 4826,
        darkEvents: 0,
      },
    ],
  },
]
