FROM python:3.12.2-alpine3.18

WORKDIR /home

ADD addons/images/count_metric/crontab .
ADD addons/images/count_metric/requirements.txt .
ADD addons/images/count_metric/*.py .
ADD common/*.py ./common/

RUN pip3 install -r requirements.txt

# fix the line endings from windows
RUN dos2unix /home/crontab
RUN crontab /home/crontab

CMD ["crond", "-f"]
