FROM python:3.12.2-alpine3.18

WORKDIR /home

COPY addons/images/count_metric/crontab .
COPY addons/images/count_metric/requirements.txt .
COPY addons/images/count_metric/*.py .
COPY common/*.py ./common/

RUN pip3 install -r requirements.txt

# fix the line endings from windows
RUN dos2unix /home/crontab && crontab /home/crontab

CMD ["crond", "-f"]
