FROM python:3.12.0-alpine3.18

WORKDIR /home

ADD addons/images/rsu_ping_fetch/crontab .
ADD addons/images/rsu_ping_fetch/requirements.txt .
ADD addons/images/rsu_ping_fetch/*.py .
ADD common/*.py ./common/

RUN pip3 install -r requirements.txt
# fix the line endings from windows
RUN dos2unix /home/crontab

RUN crontab /home/crontab

CMD ["crond", "-f"]