FROM python:3.12.2-slim

WORKDIR /home

ADD addons/images/count_metric/requirements.txt .
ADD addons/images/count_metric/*.py .
ADD common/*.py ./common/

RUN pip3 install -r requirements.txt

CMD ["/home/driver.py"]
ENTRYPOINT ["python3"]