FROM python:3.12.0-alpine3.18

WORKDIR /home

ADD addons/images/rsu_ping/crontab.rsu_pinger ./crontab
ADD addons/images/rsu_ping/requirements.txt .
ADD addons/images/rsu_ping/rsu_pinger.py .
ADD addons/images/rsu_ping/purger.py .
ADD common/*.py ./common/

RUN pip3 install -r requirements.txt
# fix the line endings from windows
RUN dos2unix /home/crontab

RUN crontab /home/crontab

CMD ["crond", "-f"]