FROM python:3.12.2-alpine3.18

WORKDIR /home

ADD addons/images/bsm_query/requirements.txt .
ADD addons/images/bsm_query/*.py .

RUN pip3 install -r requirements.txt

CMD ["/home/bsm_query.py"]
ENTRYPOINT ["python3"]