FROM python:3.12-slim

WORKDIR /home

ADD addons/images/firmware_manager/requirements.txt .
ADD addons/images/firmware_manager/resources/xfer_yunex.jar ./tools/
ADD addons/images/firmware_manager/*.py .
ADD common/*.py ./common/

RUN pip3 install -r requirements.txt
RUN apt-get update
RUN apt-get install -y default-jdk

CMD ["/home/firmware_manager.py"]
ENTRYPOINT ["python3"]