const cv_manager_user = process.env.MONGO_ADMIN_DB_USER
const cv_manager_pass = process.env.MONGO_ADMIN_DB_PASS
const database = process.env.MONGO_DB_NAME || 'ConflictMonitor'

db = connect('mongodb://' + cv_manager_user + ':' + cv_manager_pass + '@mongo:27017/')
if (db === null) {
  print('Error connecting to the MongoDB instance')
} else {
  print('Successfully connected to the MongDB instance')
}

var currentDate = new Date()
var currentDateIso = currentDate.toISOString().slice(0, -5)

var datePreviousHour = new Date()
datePreviousHour.setHours(currentDate.getHours() - 1)
var datePreviousHourIso = datePreviousHour.toISOString().slice(0, -5)

database = db.getSiblingDB(database)

// insert OdeSsmJson document
database.OdeSsmJson.insertOne({
  metadata: {
    logFileName: '',
    recordType: 'ssmTx',
    securityResultCode: 'success',
    receivedMessageDetails: { rxSource: 'NA' },
    payloadType: 'us.dot.its.jpo.ode.model.OdeSsmPayload',
    serialId: {
      streamId: 'daccfc21-e356-4481-be37-5963a056bfc0',
      bundleSize: 1,
      bundleId: 0,
      recordId: 0,
      serialNumber: 0,
    },
    odeReceivedAt: currentDate,
    schemaVersion: 6,
    maxDurationTime: 0,
    recordGeneratedAt: '',
    recordGeneratedBy: 'RSU',
    sanitized: false,
    odePacketID: '',
    odeTimStartDateTime: '',
    originIp: '10.0.0.78',
    ssmSource: 'RSU',
  },
  payload: {
    data: {
      second: 0,
      status: {
        signalStatus: [
          {
            sequenceNumber: 0,
            id: {
              id: 12110,
            },
            sigStatus: {
              signalStatusPackage: [
                {
                  requester: {
                    id: {
                      stationID: 2366845094,
                    },
                    request: 3,
                    sequenceNumber: 0,
                    typeData: {
                      role: 'publicTransport',
                    },
                  },
                  inboundOn: {
                    lane: 2,
                  },
                  status: 'granted',
                },
              ],
            },
          },
        ],
      },
    },
    dataType: 'us.dot.its.jpo.ode.plugin.j2735.J2735SSM',
  },
})

msgTimeDeltaSeconds = 60
// Function to create a new date with added seconds
function addSeconds(date, seconds) {
  let newDate = new Date(date)
  newDate.setSeconds(newDate.getSeconds() + seconds)
  return newDate
}

// Processed BSM with a ID of (ABC12345)
let messageCount = 0
database.ProcessedBsm.insertMany([
  {
    geometry: {
      coordinates: [-104.9029669, 39.6283543],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 56801,
      heading: 98,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 16,
      speed: 15.32,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9029669, 39.6283543],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 56801,
      heading: 98,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 16,
      speed: 15.32,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9029053, 39.6284321],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 27200,
      heading: 276.4,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 109,
      speed: 18.32,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9029053, 39.6284321],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 27200,
      heading: 276.4,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 109,
      speed: 18.32,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9032622, 39.6283611],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 25801,
      heading: 96.3,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 119,
      speed: 15.24,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9032622, 39.6283611],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 25801,
      heading: 96.3,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 119,
      speed: 15.24,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9033877, 39.628385],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 18300,
      heading: 95.3,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 45.0006867968,
        semiMajor: 2,
      },
      msgCnt: 115,
      speed: 16.34,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9033877, 39.628385],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 18300,
      heading: 95.3,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 45.0006867968,
        semiMajor: 2,
      },
      msgCnt: 115,
      speed: 16.34,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9036848, 39.6284042],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 52700,
      heading: 92.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 103,
      speed: 15.12,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9036848, 39.6284042],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 52700,
      heading: 92.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 103,
      speed: 15.12,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9038101, 39.6284868],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 31400,
      heading: 272.1,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 23,
      speed: 18.9,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9038101, 39.6284868],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 31400,
      heading: 272.1,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 23,
      speed: 18.9,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9032335, 39.6284547],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 34100,
      heading: 275.3,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 57,
      speed: 17.14,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9032335, 39.6284547],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 34100,
      heading: 275.3,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 57,
      speed: 17.14,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9045055, 39.6284844],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 40400,
      heading: 268.7,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 120,
      speed: 16.96,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9045055, 39.6284844],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 40400,
      heading: 268.7,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 120,
      speed: 16.96,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9043971, 39.6284081],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 48600,
      heading: 88.9,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 62,
      speed: 14.22,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9043971, 39.6284081],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 48600,
      heading: 88.9,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 62,
      speed: 14.22,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9040653, 39.6284864],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 38200,
      heading: 270.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 98,
      speed: 17.64,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9040653, 39.6284864],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 38200,
      heading: 270.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 98,
      speed: 17.64,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9046871, 39.6284785],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 35400,
      heading: 266.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 45.0006867968,
        semiMajor: 2,
      },
      msgCnt: 64,
      speed: 18.56,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'ABC12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9046871, 39.6284785],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 35400,
      heading: 266.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 45.0006867968,
        semiMajor: 2,
      },
      msgCnt: 64,
      speed: 18.56,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.904749, 39.6283763],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 17600,
      heading: 86.2,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 37,
      speed: 14.38,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.904749, 39.6283763],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 17600,
      heading: 86.2,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 37,
      speed: 14.38,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9047687, 39.6284629],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 299,
      heading: 153.1,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 89,
      speed: 23.92,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9047687, 39.6284629],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 299,
      heading: 153.1,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 89,
      speed: 23.92,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9048606, 39.6283854],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 10299,
      heading: 86.5,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 34,
      speed: 14.14,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9048606, 39.6283854],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 10299,
      heading: 86.5,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 34,
      speed: 14.14,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9050532, 39.6283752],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 44400,
      heading: 83.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 20,
      speed: 12.5,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9050532, 39.6283752],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 44400,
      heading: 83.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 20,
      speed: 12.5,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9057596, 39.6283846],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 47001,
      heading: 259.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 58,
      speed: 15.74,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9057596, 39.6283846],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 47001,
      heading: 259.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 58,
      speed: 15.74,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9055467, 39.6284118],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 39600,
      heading: 261.4,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 106,
      speed: 17.38,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9055467, 39.6284118],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 39600,
      heading: 261.4,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 106,
      speed: 17.38,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9056468, 39.6283081],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 4999,
      heading: 79.1,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 109,
      speed: 11.46,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9056468, 39.6283081],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 4999,
      heading: 79.1,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 0,
        semiMajor: 2,
      },
      msgCnt: 109,
      speed: 11.46,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9054233, 39.6283188],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 13300,
      heading: 80.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 122,
      speed: 12.54,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
  {
    geometry: {
      coordinates: [-104.9054233, 39.6283188],
      type: 'Point',
    },
    type: 'Feature',
    properties: {
      validationMessages: [],
      schemaVersion: 8,
      secMark: 13300,
      heading: 80.8,
      brakes: {
        scs: 'unavailable',
        wheelBrakes: {
          leftFront: false,
          rightFront: false,
          unavailable: true,
          leftRear: false,
          rightRear: false,
        },
        abs: 'unavailable',
        traction: 'unavailable',
        brakeBoost: 'unavailable',
        auxBrakes: 'unavailable',
      },
      accuracy: {
        semiMinor: 2,
        orientation: 90.0013735936,
        semiMajor: 2,
      },
      msgCnt: 122,
      speed: 12.54,
      timeStamp: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      transmission: 'UNAVAILABLE',
      messageType: 'BSM',
      size: {
        width: 0,
        length: 0,
      },
      accelSet: {
        accelVert: -127,
        accelLat: 2001,
        accelYaw: 0,
        accelLong: 2001,
      },
      id: 'DEF12345',
      odeReceivedAt: addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString(),
      originIp: '8.8.8.8',
    },
    recordGeneratedAt: addSeconds(currentDate, messageCount++ * msgTimeDeltaSeconds),
  },
])

print('start date', addSeconds(currentDate, 0).toISOString())
print('end date', addSeconds(currentDate, messageCount * msgTimeDeltaSeconds).toISOString())

print('messageCount', messageCount)

print('Successfully inserted sample data')
