# Pipeline for creating and pushing artifacts for all services

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - 'resources/intersection-api/*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'resources/intersection-api'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Publish the artifacts directory for consumption in publish pipeline
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'jpo-cvmanager-intersection-api'
      publishLocation: 'Container'
