type FEATURE_KEY_RSU = 'rsu'
type FEATURE_KEY_INTERSECTION = 'intersection'
type FEATURE_KEY_WZDX = 'wzdx'
type FEATURE_KEY_HAAS = 'haas'
type FEATURE_KEY_RSU_STATUS_MONITOR = 'rsuStatusMonitor'

type FEATURE_KEY =
  | FEATURE_KEY_RSU
  | FEATURE_KEY_INTERSECTION
  | FEATURE_KEY_WZDX
  | FEATURE_KEY_HAAS
  | FEATURE_KEY_RSU_STATUS_MONITOR

interface FlaggedElem {
  tag?: FEATURE_KEY
}