type NotificationType =
  | 'IntersectionReferenceAlignmentNotification'
  | 'SignalGroupAlignmentNotification'
  | 'SpatMinimumDataNotification'
  | 'MapMinimumDataNotification'
  | 'SpatBroadcastRateNotification'
  | 'MapBroadcastRateNotification'
  | 'SignalStateAssessmentNotification'
  | 'LaneDirectionOfTravelAssessmentNotification'
  | 'ConnectionOfTravelNotification'
  | 'SignalStateConflictNotification'
  | 'TimeChangeDetailsNotification'
